Feat/hook form
sekcja-memow/flankers pull request #22
Opened 2020-12-23 23:05 UTC by SikoraKam

2020-12-27 21:00 UTC, MrPumpking requested changes

2020-12-27 21:00 UTC, miikebar commented on app/src/hooks/useEditProfileMutation.ts
> +  newPassword: string;
Moim zdaniem lepiej żeby payload miał taką strukturę jakiej oczekuje backend - `password` zamiast `newPassword`

2020-12-27 21:00 UTC, miikebar commented on app/src/hooks/useTeamInvitationMutation.ts
> +  team_id: number | null | undefined;
Payload do backendu nie przyjmuje undefined ani null, więc tutaj też nie powinien. Jeżeli query / mutation zależy od danych, które mogę nie być od razu dostępne należy skorzystać z tej opcji: https://react-query.tanstack.com/guides/dependent-queries

2020-12-27 21:00 UTC, miikebar commented on app/src/screens/profile/ProfileEditScreen.tsx
> +  const [isPending, setPending] = useState(false);
Zamiast `isPending` używać state zwracany przez mutation (https://react-query.tanstack.com/guides/mutations)

2020-12-27 21:00 UTC, miikebar commented on app/src/screens/profile/ProfileEditScreen.tsx
>              style={{ marginBottom: 7 }}
Każdy AppInput ma taki sam marginBottom, utwórz dla nich styl zamiast powtarzać wartość

2020-12-27 21:00 UTC, miikebar commented on app/src/screens/profile/ProfileEditScreen.tsx
> +          labelColor={useTheme().colors.white}
Nie używaj tak hooka. Zamiast tego przed returnem zdefiniuj sobie zmienną przechowującą wartość zwróconą przez useTheme

```ts
const  theme = useTheme()
```

2020-12-27 21:00 UTC, miikebar commented on app/src/screens/teams/TeamCreateScreen.tsx
>    const [description, setDescription] = useState('');
Tworzenie zespołu nie jest przeniesione na hook-form

2020-12-27 21:00 UTC, MrPumpking commented on app/src/screens/teams/TeamInvitationScreen.tsx
> +  const [isPending, setPending] = useState(false);
Zamiast tego wykorzystać state zwracany przez `mutation`

2020-12-27 21:00 UTC, MrPumpking commented on app/src/screens/teams/TeamInvitationScreen.tsx
> +      console.log('======>', error.response);
Usunąć console.log

2020-12-29 13:27 UTC, KalitaKonrad commented on app/src/screens/profile/ProfileEditScreen.tsx
> +    .oneOf([yup.ref('newPassword'), null], 'Hasła muszą się zgadzać')
Może tekst: "Hasła muszą być identyczne."

2020-12-29 13:27 UTC, KalitaKonrad commented on app/src/screens/profile/ProfileEditScreen.tsx
> +      console.log('ZMIANA DANYCH UDANA');
Usunąć `console.log`

2020-12-29 13:28 UTC, KalitaKonrad commented on app/src/hooks/useEditProfileMutation.ts
> +        console.log('1111WITAMMMMM');
Usunąć `console.log`

2020-12-29 13:28 UTC, KalitaKonrad commented on app/src/screens/profile/ProfileEditScreen.tsx
> +    console.log('CZEKAM');
Usunąć `console.log`

2020-12-29 13:30 UTC, SikoraKam commented on app/src/screens/profile/ProfileEditScreen.tsx
> +    console.log('CZEKAM');
byczq do tej outdated, sprawdz najnowsza wersje

2020-12-29 13:30 UTC, KalitaKonrad commented on app/src/screens/profile/ProfileEditScreen.tsx
> +  // const [username, setUsername] = React.useState('');
Należy usunąć kod, który jest wykomentowany, a nie jest zwykłym komentarzem.

2020-12-29 13:35 UTC, KalitaKonrad commented on app/src/hooks/useTeamInvitationMutation.ts
> +        console.log('JEST  W PYTE');
Usunąć console.log

2020-12-29 16:31 UTC, MrPumpking approved these changes

2020-12-29 16:31 UTC, MrPumpking commented on app/src/hooks/useTeamInvitationMutation.ts
> +        console.log(error);
Użytkownik nie zobaczy console.log. Lepiej poinformować go o błędzie np. poprzez `alert(msg)`

2020-12-29 18:02 UTC, merged