Push Notifications
sekcja-memow/flankers pull request #30
Opened 2021-01-10 11:11 UTC by KalitaKonrad

Handling notifications IMO should be handled via `handleNotifiationPress` function in `notificationHandler`. We would pass as data some kind of an event and and function would be called dynamically based on that event.
I've set up eventlistener in the `App.tsx` which listens for any `NOTIFICATION_EVENT` events and based on `data` property in that event it will call function referring to that event :)

2021-01-10 17:16 UTC, MrPumpking requested changes

2021-01-10 17:16 UTC, miikebar commented on app/src/hooks/useNotification.tsx
> +  };
Chyba nie będziemy wysyłać powiadomień z klienta więc można to wywalić

2021-01-10 17:16 UTC, miikebar commented on app/src/hooks/useNotification.tsx
> +    if (Constants.isDevice) {
Można się pozbyć zagnieżdżenia

```suggestion
    if (!Constants.isDevice) {
      return;
    }
```

2021-01-10 17:16 UTC, miikebar commented on app/src/hooks/useNotification.tsx
> +      }
Nie musisz ręcznie sprawdzać statusu - z dokumentacji Permissions.askAsync(): "Prompt the user for types of permissions. If they have already granted access, response will be success.". Możesz po prostu zawsze wywoływać `askAsync` i sprawdzać status. (https://docs.expo.io/versions/latest/sdk/permissions/#permissionsaskasynctypes)

2021-01-10 17:16 UTC, miikebar commented on app/src/hooks/useNotification.tsx
> +        alert('Failed to get push token for push notification!');
Wszędzie używamy polskiego podczas komunikacji z userem więc tutaj też pasuje podmienić

2021-01-10 17:16 UTC, miikebar commented on app/src/hooks/useNotification.tsx
> +      alert('Must use physical device for Push Notifications');
Tak samo jak wyżej

2021-01-10 17:16 UTC, miikebar commented on app/src/hooks/useNotification.tsx
> +    }
Jeżeli wykona się return z tokenem ze 110 linii to ten kod nigdy się nie wykona. Czy tak ma być?

2021-01-10 17:16 UTC, MrPumpking commented on app/src/hooks/useNotification.tsx
> +  const responseListener = useRef<Subscription>();
Jaki jest cel przechowywania listenerów jako refów? Są używane tylko w `useEffect`

2021-01-10 17:16 UTC, MrPumpking commented on app/src/hooks/useNotification.tsx
> +      notificationListener.current = Notifications.addNotificationReceivedListener(
`addNotificationReceivedListener` zwraca subscription, którego potem można użyć żeby usunąć listener. (https://docs.expo.io/versions/v40.0.0/sdk/notifications/#addnotificationreceivedlistenerlistener-event-notification--void-void)

```suggestion
      const subscription = Notifications.addNotificationReceivedListener(
```

2021-01-10 17:16 UTC, MrPumpking commented on app/src/hooks/useNotification.tsx
> +      responseListener.current = Notifications.addNotificationResponseReceivedListener(
Tak samo jak wyżej (https://docs.expo.io/versions/v40.0.0/sdk/notifications/#addnotificationresponsereceivedlistenerlistener-event-notificationresponse--void-void)

2021-01-10 17:16 UTC, MrPumpking commented on app/src/hooks/useNotification.tsx
> +        Notifications.removeNotificationSubscription(responseListener);
Po zmianach  z góry można wywołać `subscription.remove()`

2021-01-10 17:16 UTC, MrPumpking commented on app/src/hooks/useNotification.tsx
> +    initNotificationUsage();
`initNotificationUsage` zwraca funkcję, która robi cleanup listenerów, natomiast Twój `useEffect` już niczego nie zwraca, więc cleanup nie zostanie nigdy wywołany. Dodaj `return initNotificationUsage();`

2021-01-10 17:16 UTC, MrPumpking commented on app/src/hooks/useNotification.tsx
> +    );
Mógłbyś też przekazywać nowy token podczas emitowania `NOTIFICATION_TOKEN_CHANGED_EVENT`

2021-01-10 17:16 UTC, MrPumpking commented on app/src/screens/ranking/RankingScreen.tsx
>      <>
Po co nam ten fragment?

2021-01-10 17:16 UTC, MrPumpking commented on app/src/utils/notificationHandler.ts
> +};
Mam wrażenie, że handlowanie eventów będzie wygodniejsze w componentach, bo będziemy mieli dostęp do chociażby `navigation`

2021-01-10 17:16 UTC, MrPumpking commented on app/src/utils/tokenUtils.ts
> +// NOTIFICATION TOKEN
Usunąć zbędny komentarz

2021-01-10 17:16 UTC, MrPumpking commented on app/src/screens/AppScreen.tsx
> +  // useNotification();
Usunąć zbędne komentarze

2021-01-17 18:15 UTC, MrPumpking approved these changes

2021-01-17 18:28 UTC, merged