Add placeholders and loading across all screens
sekcja-memow/flankers pull request #45
Opened 2021-01-15 15:55 UTC by KalitaKonrad

No loading when there is no real data fetching functionality.

2021-01-15 19:57 UTC, MrPumpking requested changes

2021-01-15 19:57 UTC, MrPumpking commented on app/src/components/shared/AppButton.tsx
> +    loading={props.isLoading}
Prop `isLoading` jest niepotrzebny - Button ma już prop `loading`, więc z niego korzystajmy.

2021-01-15 19:57 UTC, MrPumpking commented on app/src/components/shared/Avatar.tsx
> +          },
Zróbmy jakieś zmienne na te style z użyciem useMemo, bo się powtarza to samo w 2 miejscach.

2021-01-15 19:57 UTC, MrPumpking commented on app/src/components/shared/Avatar.tsx
> +            },
Tak jak wyżej

2021-01-15 19:57 UTC, MrPumpking commented on app/src/components/shared/Avatar.tsx
>          },
Powtarzające się style z poprzednich commentów

2021-01-15 19:57 UTC, MrPumpking commented on app/src/components/shared/Avatar.tsx
> +          },
Powtarzające się style z poprzednich commentów

2021-01-15 19:57 UTC, MrPumpking commented on app/src/components/shared/Avatar.tsx
> +  const avatarPlaceholder = require('../../../assets/versioned_initial_avatar.png').toString();
Ten require moze być poza componentem

2021-01-15 19:57 UTC, MrPumpking commented on app/src/components/team/TeamMembersList.tsx
> +    ) : (
Do usunięcia - wykorzystujemy już ListPlaceholder

2021-01-15 19:57 UTC, MrPumpking commented on app/src/screens/ranking/RankingScreen.tsx
> +      )}
Switch jest elementem interfejsu - nie robimy dla niego skeleton loadera. Zamiast tego zmiana tabów powinna być zablokowana dopóki ranking nie zostanie pobrany.

2021-01-15 19:57 UTC, MrPumpking commented on app/src/screens/ranking/RankingScreen.tsx
>          alert('Błąd podczas wyświetlania rankungu użytkowników')
Wyświetlanie alertu przenieść do `useEffect`

```ts
useEffect(() => {
  if (query.isError) {
    alert(...); 
  }
}, [query.isError])
```

Można by też ustawić tytuł alertu - https://docs.expo.io/versions/latest/react-native/alert/#example

2021-01-15 19:57 UTC, MrPumpking commented on app/src/screens/ranking/RankingScreen.tsx
>          alert('Błąd podczas wyświetlania rankingu drużynowego')
Tak jak wyżej

2021-01-15 19:57 UTC, MrPumpking commented on app/src/screens/teams/TeamInvitationScreen.tsx
> +      avatar={{ uri: userProfile?.data?.teams?.[0].versioned_avatar }}>
Z tej konstrukcji korzystamy w wielu miejscach - może warto zrobić hook `useUserTeam`, który w środku wywołuje `useUserProfile` i zwraca `userProfile.data.teams[0]`

2021-01-15 19:57 UTC, MrPumpking commented on app/src/screens/teams/TeamManageScreen.tsx
> +    }
Można by skorzystać z `else if`

2021-01-15 23:16 UTC, KalitaKonrad commented on app/src/screens/ranking/RankingScreen.tsx
> +      )}
True.

2021-01-16 18:12 UTC, MrPumpking approved these changes

2021-01-16 18:12 UTC, merged