Feat/teams
sekcja-memow/flankers pull request #5
Opened 2020-12-08 22:08 UTC by SikoraKam

TeamScreen functionalities. In future add modal component dependent on action from user

2020-12-08 22:19 UTC, MrPumpking requested changes

2020-12-08 22:19 UTC, MrPumpking commented on app/src/components/shared/Switch.tsx
> +        value === 'left' ? setLeftBtnIsActive(true) : setLeftBtnIsActive(false);
Skoro mamy tylko 2 wartości to możemy zrobić po prostu toggle
```js
setLeftBtnIsActive(!leftBtnIsActive)
```

2020-12-08 22:19 UTC, MrPumpking commented on app/src/components/shared/Switch.tsx
> +  const [leftBtnIsActive, setLeftBtnIsActive] = useState<boolean>(true);
Takie zmienne warto zaczynać od `is` lub `has`, są wtedy bardziej czytelne, np: `isLeftButtonActive`

2020-12-08 23:49 UTC, MrPumpking approved these changes

2020-12-09 12:35 UTC, merged

2020-12-09 12:35 UTC, macieklad approved these changes